# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=5)),
                ('last_modified', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(default=3)),
                ('culture', models.IntegerField(default=3)),
                ('infrastructure', models.IntegerField(default=3)),
                ('green', models.IntegerField(default=3)),
                ('safety', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ('last_modified',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('user_id', 'zipcode')]),
        ),
    ]
